name: Python application

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    name: Run tests & display coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: install
        run: pip install coverage
        
      - name: run test
        run: coverage run -m postinumerot_test
        
      - name: coverage report
        run: coverage report
